version: "3.9"

services:
  poke:
    build:
      context: poke_py/.
      dockerfile: Dockerfile
    volumes:
      - ./poke_py/:/app
    ports:
      - "8080:8080"
  poke-unit:
    extends: poke
    command: python -m pytest tests/
