version: "3.9"

services:
  poke:
    build:
      context: poke_rb/.
      dockerfile: Dockerfile
    volumes:
      - ./poke_rb/:/app
    ports:
      - "8080:8080"
    depends_on:
      - mock-server
