version: "3.9"

services:
  poke-py:
    build:
      context: poke_py/.
      dockerfile: Dockerfile
      # target: poke-py-service
    volumes:
      - ./poke_py/:/app
    command: python app.py
    ports:
      - "8080:8080"
  # poke-test:
  #   extends:
  #     service: poke
  #   build:
  #     target: poke-tests
  #   command: python -m pytest tests/
