version: "3.9"

services:
  mock-server:
    build:
      context: mock_server/.
      dockerfile: Dockerfile
    volumes:
      - ./mock_server/:/app
    environment:
      - HOST_PORT=0.0.0.0:5000
    expose:
      - "5000"
    ports:
      - "8081:5000"
  poke:
    # Each implementation should define its own compose file
    # with `poke` service and provide instructions how to build it.
    # The only condition - it needs to have 8080 port exposed.
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - POKEAPI_BASE_URL
      - FUNTRANS_BASE_URL
    depends_on:
      - mock-server
  int-tests:
    build:
      context: int_tests/.
      dockerfile: Dockerfile
    volumes:
      - ./int_tests/:/app
    environment:
      - SERVICE_HOST=poke:8080
    depends_on:
      - mock-server
      - poke
