version: "3.9"

services:
  mock-server:
    build:
      context: mock_server/.
      dockerfile: Dockerfile
    volumes:
      - ./mock_server/:/app
    environment:
      - HOST_PORT=0.0.0.0:5000
    expose:
      - "5000"
    ports:
      - "8081:5000"
  poke-py:
    build:
      context: poke_py/.
      dockerfile: Dockerfile
    volumes:
      - ./poke_py/:/app
    command: python app.py
    expose:
      # NOTE: Each implementation is expected to expose 8080 port.
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - POKEAPI_BASE_URL
  int-tests:
    build:
      context: int_tests/.
      dockerfile: Dockerfile
    volumes:
      - ./int_tests/:/app
